default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['VOLUNTEER_HUB_DATABASE_USERNAME'] %>
  password: <%= ENV['VOLUNTEER_HUB_DATABASE_PASSWORD'] %>
  host: <%= ENV['VOLUNTEER_HUB_DATABASE_HOST'] %>

development:
  <<: *default
  database: <%= ENV['VOLUNTEER_HUB_DATABASE_NAME'] %>

test:
  <<: *default
  database: <%= ENV['VOLUNTEER_HUB_DATABASE_TEST_NAME'] %>
  template: template0

production:
  <<: *default
  database: <%= ENV['VOLUNTEER_HUB_DATABASE_NAME'] %>
  username: <%= ENV['VOLUNTEER_HUB_DATABASE_USERNAME'] %>
  password: <%= ENV['VOLUNTEER_HUB_DATABASE_PASSWORD'] %>
